### ISSUE TITLE
Might be broken on API 10

### ISSUE THREAD

**Issue by Frenzie** [koreader/android-luajit-launcher#81]
Needs checking.

Copied from https://github.com/koreader/koreader/issues/3409#issuecomment-338774390

On API 10 (2.3) there's another error still:

```
E/AndroidRuntime( 1487): FATAL EXCEPTION: Thread-10
E/AndroidRuntime( 1487): java.lang.NoSuchMethodError: android.view.Display.getSize
E/AndroidRuntime( 1487): 	at org.koreader.launcher.MainActivity.getSceenSize(MainActivity.java:246)
E/AndroidRuntime( 1487): 	at org.koreader.launcher.MainActivity.getScreenWidth(MainActivity.java:255)
E/AndroidRuntime( 1487): 	at dalvik.system.NativeStart.run(Native Method)
W/ActivityManager( 1219):   Force finishing activity org.koreader.launcher/.MainActivity
```

That should be easy enough to get around (see, e.g., [here](https://stackoverflow.com/q/11647817/2470572)), but this should also be an issue on ARM. Introduced by https://github.com/koreader/android-luajit-launcher/pull/56
